### ISSUE TITLE
Get a dummy service running in AWS (walking skeleton)

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/checkmate#1]
### Tasks

* [x] Add boilerplate to create a web-app with tests, formatting, dev etc. - https://github.com/hypothesis/checkmate/pull/14
* [x] Add a status end-point
* [x] Add a dummy URL checking end-point (`/api/url`)
* [x] Get to 100% test coverage + lint + formatting etc.
* [x] Make sure the above run in Github Actions
* [x] Add boilerplate for deployment (_in place, but untested_)
* [x] Create `prod` and `qa` environments in AWS
* [x] Add config for the project in the `deployment` repo
* [x] Configure Jenkins to deploy it

### Acceptance criteria

* [x] There is a service running in AWS which will respond to calls to `/api/url` for checking URLs with 204 (no content required)
* ~The service is accessible via the AWS internal name inside AWS (_true, but not accessible from ViaHTML_)~ - This has been replaced with this: https://github.com/hypothesis/playbook/issues/468
* [x] The service is **not** accessible on a pretty name (_It is, but `/api` isn't, so this is actually better_)
* [x] The service is running on one large host, rather than many

## Why one host?

We plan to have automated downloading of various tasks etc, but this causes a problem if we have many instances. Who should do it?

This is something [we intend to fix by implementing Celery on the boxes and integrating with `h-periodic`](https://github.com/hypothesis/checkmate/issues/6), but it's not something we need for the MVP. So for now, we'll just stand up one beefy instance instead and side step the issue.

**Comment by jon-betts** [comment]
We could do with closing this ticket out as our understanding has moved on a bit:

 * [ ] We could do with a ticket for moving ViaHTML and Via into the private subnet in AWS
 * [ ] Another ticket for giving the internal name an SSL certificate that checks out (Phase 2)
