### ISSUE TITLE
Ensure downstream services mark malicious content clearly for users

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/checkmate#10]
Currently Via and ViaHTML give a pretty milquetoast response if something is blocked for any reason. We need to much more assertive if the reason we are blocking is because the content is malicious.

### Tasks

 * [x] Implement a variation of the page in ViaHTML if the reason is "malicious" - https://github.com/hypothesis/viahtml/pull/36
 * [x] This page should not include a direct link to the content
 * [x] Retro fit this into Via somehow - https://github.com/hypothesis/via/pull/266

**Comment by jon-betts** [comment]
Done!
