### ISSUE TITLE
Implement a checking service

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/checkmate#13]
* [ ] Pick and register with an external threat detection system - https://github.com/hypothesis/checkmate/issues/4
 * [ ] Ensure downstream services mark malicious content clearly for users - https://github.com/hypothesis/checkmate/issues/10
 * [ ] Get a dummy service running in AWS (walking skeleton) - https://github.com/hypothesis/checkmate/issues/1
 * [ ] Mirror existing blocklist functionality in Via / ViaHTML - https://github.com/hypothesis/checkmate/issues/2
 * [ ] Add minimal logging, monitoring and alerting to checkmate - https://github.com/hypothesis/checkmate/issues/7
 * [ ] Retrofit checkmate as the blocking service for Via / ViaHTML -  https://github.com/hypothesis/checkmate/issues/3
 * [ ] Integrate external threat tracking into the replies we send - https://github.com/hypothesis/checkmate/issues/5
 * [ ] Allow the service to run on multiple instances - https://github.com/hypothesis/checkmate/issues/6
