### ISSUE TITLE
Mirror existing blocklist functionality in Via / ViaHTML

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/checkmate#2]
Update the service to use the same list as Via to implement blocking information. We can directly include the info in the service, but I think we might not want to commit the list.

Instead we can probably directly lift and shift the implementation in ViaHTML for now.

### Tasks

 * [x] Design the API
 * [x] Document it in the README
 * [x] Implement

### Acceptance criteria

 * [x] The URL responds with either 204 OK when everything is fine
 * [x] A different response when advising a block (MAYBE?)
 * [x] The reasons for the block (so a client can choose to disregard)
 * [x] The maxiumum severity of the block (is this optional or mandatory, e.g. malicious content **must** be blocked regardless of what you think about it)

### Implementation notes

We should take the opportunity to change the data model to allow some other things:

 * Multiple reasons ("it's got images, video and makes a lot of ajax requests") then the client can check if they care
 * Suggested severity levels so that an overall worst severity can be set
 * This allows us to differentiate between "you might want to block this" and "you must block this"
