### ISSUE TITLE
Integrate URLHaus into the replies we send

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/checkmate#37]
This is intertwined with a number of other issues:

* https://github.com/hypothesis/checkmate/issues/6 - Allow the service to run on multiple instances
* https://github.com/hypothesis/checkmate/issues/8 - Allow the blocklist to be administrated from a UI for support staff

This is because:

 * We need a DB to store the results
 * As we have multiple instances, we need a solution to allow us to update the DB just the once.

### Tasks

 * [x] Create all the basic scaffold for the project to get DB and Celery integrated - https://github.com/hypothesis/checkmate/pull/32 
 * [x] Enable storing the existing blocklist in the database - https://github.com/hypothesis/checkmate/pull/35
 * [x] Add a celery task and worker to update it - https://github.com/hypothesis/checkmate/pull/36 
 * [x] Enable running celery tasks from `h-periodic` 
    * [x] https://github.com/hypothesis/h-periodic/pull/35 - Add the scripts to allow easy `make requirements`
    * [x] https://github.com/hypothesis/h-periodic/pull/36 - Add the scaffold required to start writing tests with `make test`
    * [x] https://github.com/hypothesis/h-periodic/pull/38 - Namespace the h-beat so we can add another along side it
    * [x] https://github.com/hypothesis/h-periodic/pull/37 - Separate status reporting out for `h` and return all failures rather than 
the first
    * [x] https://github.com/hypothesis/h-periodic/pull/39 - Add checkmate beat and include it in the status page (in QA, but bugged)
    * [x] :beetle: https://github.com/hypothesis/checkmate/pull/47 - Exit on failure to start the app for the Celery worker
    * [x] :beetle: https://github.com/hypothesis/h-periodic/pull/40 - Fix checkmate celery queue to match the settings in Checkmate
    * [x] Remember to remove `BROKER_URL` from `h-periodic` in AWS
 * [x] Remove the old file based blocklist - https://github.com/hypothesis/checkmate/pull/43
    * [x] :beetle: https://github.com/hypothesis/checkmate/pull/48 - Fix the config
 * [ ] Use all of the above to deliver a URLHaus solution
    * [x] https://github.com/hypothesis/checkmate/pull/49  - Split out mixins
    * [x] https://github.com/hypothesis/checkmate/pull/51 - DB migration script
    * [x] :beetle: https://github.com/hypothesis/checkmate/pull/52 - Fix bugs in alembic database DSN
    * [x] https://github.com/hypothesis/deployment/pull/177 - DB migration task in Jenkins
    * [x] Migrate QA and Live
    * [x] https://github.com/hypothesis/checkmate/pull/50 - Add URLHaus checker (without using it)
    * [x] https://github.com/hypothesis/checkmate/pull/25 - Integrate URLHaus
    * [x] https://github.com/hypothesis/h-periodic/pull/41 - h-periodic calls to sync URLHaus
    * [x] :beetle: https://github.com/hypothesis/checkmate/pull/54 - Longer timeouts
    * [x] https://github.com/hypothesis/h-periodic/pull/42 - Testing schedule
    * [x] Re-implement regular schedule

### Notes

DB connection details here: https://hypothes-is.slack.com/archives/CR3E3S7K8/p1607093496497300?thread_ts=1605260202.412800&cid=CR3E3S7K8

**Comment by jon-betts** [comment]
There's some follow up work to try and clean up issues we have with this, but it is done.
