### ISSUE TITLE
Allow the service to run on multiple instances

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/checkmate#6]
In https://github.com/hypothesis/checkmate/issues/1 we specified a single large instance to simplify the deployment and MVP.

This isn't really going to do long term, so we should make sure the service can run with a proper distributed architecture:

### Tasks

 * [x] Add celery to the instances
 * [x] Add tasks for any sync jobs
 * [x] Add configuration to `h-periodic` to call the tasks
 * [x] Remove the local alternatives to this
 * [x] Attempt to tune the sizes and deployments to the traffic we see (we have two of the smallest instances we can, and it's totally overkill)

**Comment by jon-betts** [comment]
Done (mostly as work to get URLHaus working)
