### ISSUE TITLE
Add minimal logging, monitoring and alerting to checkmate

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/checkmate#7]
We can't really go live with a part of our infrastructure blind.

### Tasks

* [x] Integrate New Relic client in the most basic way - https://github.com/hypothesis/checkmate/pull/17
* [x] Add dead mans handle monitoring to see if the service is dead
* [x] Integrate with Papertrail
* [x] Setup a Papertrail group for the service in the UI
* [x] Integrate Sentry in the code (`h-pyramid-sentry` can probably do this for us)
* [x] Configure the deployment to send stats to sentry (The two vars I can see are `SENTRY_ENVIRONMENT` and `SENTRY_DSN`)
* [x] Get some basic alerts setup
* [x] Integrate dependabot - Is this done? How would I tell. It's in the apps in github

**Comment by indigobravo** [comment]
Point to note: NewRelic has been configured, but as it stands alerts will only go through to Slack. When we know the go-live date we should update the NR config to push alerts to PagerDuty.

**Comment by jon-betts** [comment]
We think we've configured sentry now, but it's kind of hard to tell for a few reasons:

 * Nothing is / can use this yet
 * Unless this fails, I'm not sure how we tell that Sentry is working
